### ISSUE TITLE
Setting `properties` on the feature object

### ISSUE THREAD

**Issue by yhahn** [emilymdubois/mapbox#1]
:wave:

Looking at the result of the turf buffer, it looks like it's returning a GeoJSON feature collection which is a nested object that looks like:

``` js
console.log(buffer);

{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Polygon",
            "geometry": { ... },
            "properties": { ... }
        }
    ]
}
```

To style the feature you'll want to set properties on the first feature object inside of the `features` array rather than on the base GeoJSON object.

**Comment by emilymdubois** [comment]
Thank you @yhahn :clap:

I changed the call from `buffer.properties...` to `buffer.features[0].properties...` (c95374f044a85ea3fb0383f678cbbf50acd61595). I initially created a for loop for every entry in the featureCollection (a975d365404c8e981336ca599eb0ece17447f9bf) – unnecessary in this situation, but I can see how it would be very helpful if I wanted to apply a buffer to multiple features in a given featureCollection (e.g., a 1-mile buffer radius around a series of campsites).

Thank you!
